GET http://localhost:5000/userlookup?id=6543645654

###  Student
GET http://localhost:5000/userlookup?id=2688373

### Employee
GET http://localhost:5000/userlookup?id=4749890

###
POST http://localhost:5000/pdfCreator